### ISSUE TITLE
Conflict because of quotes of keys in object

### ISSUE THREAD

**Issue by Zakhse** [V4Fire/Linters#3]
TSLint rule `object-literal-key-quotes` conflicts with ESLint rule `quote-props`

<img width="582" alt="TSLint object-literal-key-quotes error" src="https://user-images.githubusercontent.com/14364068/87585917-6ce6d180-c6e8-11ea-984d-e0547c29978f.png">
<img width="529" alt="ESLint quote-props error" src="https://user-images.githubusercontent.com/14364068/87585923-6e17fe80-c6e8-11ea-9201-cf6072146970.png">

**Comment by kobezzza** [comment]
You should disable TSLint if you switch to ESLint.
